comments/urls.py
from django.urls import path
from .views import CommentView, CommentDataView

app_name = "comments"

urlpatterns = [
    path('', CommentView.as_view(), name="comment"), 
    path('/view', CommentDataView.as_view(), name="comment_data"), 
]

djangocrudAjax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path("tasks/",include('tasks.urls')),
    path("products/",include('products.urls')),
    path("tutorial/",include('tutorial.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products.views import ProductView, ProductCategoryView

app_name = "products"

urlpatterns = [
    path('', ProductView.as_view(), name="products"), 
    path('<str:category>', ProductCategoryView.as_view(), name="products_category"), 
]

tasks/urls.py
from django.urls import path
from .views import TaskView, ViewTaskView, TaskDeleteView

app_name = "tasks"

urlpatterns = [
    path('', TaskView.as_view(), name="task"), 
    path('view', ViewTaskView.as_view(), name="view"), 
    path('view/<int:pk>', TaskDeleteView.as_view(), name="delete"), 
]

tutorial/urls.py
from django.urls import path
from tutorial.views import TutorialView, GetProductView

app_name = "tutorial"

urlpatterns = [
    path('', TutorialView.as_view(), name="index"), 
    path('<str:category>', GetProductView.as_view(), name="category"), 
]

comments/models.py
from django.db import models

class Comment(models.Model):
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

products/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length = 150)
    category = models.CharField(max_length=50)
    image = models.ImageField(upload_to="products")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.name}"
    
    

tasks/models.py
from django.db import models

class Task(models.Model):
    owner = models.CharField(max_length = 150)
    name = models.CharField(max_length = 150)
    task_date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    
    
    

tutorial/models.py
from django.db import models

# Create your models here.

comments/forms.py
from django import forms
from comments.models import Comment

class CommentForm(forms.ModelForm):
        
    class Meta:
        model = Comment
        fields = ["comment"]

products/forms.py
from django import forms
from products.models import Product

class ProductForm(forms.ModelForm):
        
    class Meta:
        model = Product
        fields = ["name", "category", "image"]

tasks/forms.py
from django import forms
from tasks.models import Task

class TaskForm(forms.ModelForm):
        
    class Meta:
        model = Task
        fields = ["owner", "name", "task_date", "start_time", "end_time"]

comments/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.template import loader
from django.views import View
from comments.forms import CommentForm
from comments.models import Comment

class CommentView(View):
    form_class = CommentForm
    def get(self, request, *args, **kwargs):
        return render(request, "comments/index.html", {})

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            form = self.form_class(request.POST)
            if form.is_valid():
                form.save()
                return JsonResponse({'message': 'success'})
            return JsonResponse({'message': 'Field couldn\'t validate'}) 
        return JsonResponse({'message': 'Wrong request'})

class CommentDataView(View):
    def get(self, request, *args, **kwargs):
        template = loader.get_template("comments/view.html")
        comments = Comment.objects.all()
        context = {
            "comment_list": comments
        }
        return HttpResponse(template.render(context, self.request))

products/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views import View
from django.shortcuts import render, redirect
from django.template import loader
from products.models import Product



class ProductView(View):
    def get(self,request, *args, **kwargs):
        products = Product.objects.values('category').distinct()
        context = {
            "product_list": products
        }
        return render(request, "products/index.html", context)

class ProductCategoryView(View):
    def get(self,request, category, *args, **kwargs):
        if request.is_ajax():
            products = Product.objects.filter(category=category)
            context = {
                "product_image_list": products
            }
            template = loader.get_template("products/category.html")
            return HttpResponse(template.render(context, self.request))
        return HttpResponse("Wrong request")

tasks/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views import View
from tasks.forms import TaskForm
from tasks.models import Task
# from django.shortcuts import render, redirect
# from django.template import loader


class TaskView(View):
    form_class = TaskForm

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            form = self.form_class(request.POST)
            if form.is_valid():
                form.save()
                return JsonResponse({"message": "success"})
            return JsonResponse({"message": "Validation failed"})
        return JsonResponse({"message": "Wrong request"})

    def get(self,request, *args, **kwargs):
        return render(request, "index.html", {})

class ViewTaskView(View):

    def get(self,request, *args, **kwargs):
        tasks = Task.objects.all()
        return render(request, "view.html", {"tasks":tasks})

class TaskDeleteView(View):
    
    def get(self,request, pk, *args, **kwargs):
        if request.is_ajax():
            task = Task.objects.get(pk=pk)
            task.delete()
            return JsonResponse({"message":"success"})
        return JsonResponse({"message": "Wrong request"})

tutorial/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views import View
from django.shortcuts import render, redirect
from django.template import loader
from products.models import Product



class TutorialView(View):
    def get(self,request, *args, **kwargs):
        products = Product.objects.values('category').distinct()
        context = {
            "product_list": products
        }
        return render(request, "tutorial/index.html", context)

class GetProductView(View):
    def get(self,request, category, *args, **kwargs):
        if request.is_ajax():
            products = Product.objects.filter(category=category).values('id', 'name')
            return JsonResponse({'data': list(products)})
        return HttpResponse('Wrong request')

templates/comments/index.html
{% extends 'layout.html' %}

{% block styles %}
<style>
    .text-red{
        color: tomato !important;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-6 offset-3">
            
            <form id="formComment" action="{% url 'comments:comment'  %}" autocomplete="off">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        <div class="form-group validate">
                            <label for="comment">Comment</label>
                            <textarea rows="5" name="comment" class="form-control" placeholder="Enter your comment"></textarea>
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    <div class="col-6">
                        <button type="submit" class="btn btn-primary pl-5 pr-5 btnSave">Save</button>
                    </div>
                </div>
            </form>

            <div class="comment-content mt-5" data-url="{% url 'comments:comment_data' %}">

            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>

    function getComments(){
        $.ajax({
            url: $(".comment-content").data('url'),
            type: "GET",
            success: function(resp){
                $(".comment-content").html(resp);
            },
            error: function(resp){
                console.log("something went wrong");
            }
        });
    }
    getComments();

    $("#formComment").on("submit", function(e){
        e.preventDefault();
        e.stopPropagation();
        var $this = $(this);
        var valid = true;
        $('#formComment textarea').each(function() {
            let $this = $(this);
            
            if(!$this.val()) {
                valid = false;
                $this.parents('.validate').find('.mySpan').text('The '+$this.attr('name').replace(/[\_]+/g, ' ')+' field is required');
            }
        });
    
        if(valid){
            $(".btnSave").text('Saving....').attr('disabled',true);
            let data = $this.serialize();
            //ajax
            $.ajax({
                url: $this.attr('action'),
                type: "POST",
                data: data,
                dataType: 'json',
                success: function(resp){
                    if(resp.message === 'success'){
                        getComments();
                    }else{
                        alert(resp.message);
                    }

                    $(".btnSave").text('Save').attr('disabled',false);
                },
                error: function(resp){
                    console.log('something went wrong');
                    $(".btnSave").text('Save').attr('disabled',false);
                }
            });
        }
        return false;
    });

</script>
{% endblock scripts %}

templates/comments/view.html
<div>
    {% for comment in comment_list %}
        <p>{{ comment.comment }}</p>
        <hr>
    {% endfor %}
</div>

templates/data.html
<table class="table">
    <thead>
        <tr>
            <th>Good</th>
            <th>Bad</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Yes</td>
            <td>No</td>
        </tr>
    </tbody>
</table>

templates/index.html
{% extends 'layout.html' %}

{% block styles %}
<style>
    .text-red{
        color: tomato !important;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-6 offset-3">
            
            <form id="formTask" action="{% url 'tasks:task'  %}" autocomplete="off">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        <div class="form-group validate">
                            <label for="owner">Owner</label>
                            <input type="text" name="owner" class="form-control" id="owner" placeholder="Enter owner name">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                        <div class="form-group validate">
                            <label for="name">Task name</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Enter task name">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                        <div class="form-group validate">
                            <label for="task_date">Task date</label>
                            <input type="date" name="task_date" class="form-control" id="task_date">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group validate">
                            <label for="start_time">Start time</label>
                            <input type="time" name="start_time" class="form-control" id="start_time">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group validate">
                            <label for="end_time">End time</label>
                            <input type="time" name="end_time" class="form-control" id="end_time">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    </div>
                    <div class="col-6">
                        <button type="submit" class="btn btn-primary pl-5 pr-5 btnSave">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    $("#formTask").on("submit", function(e){
        e.preventDefault();
        e.stopPropagation();
        var $this = $(this);
        var valid = true;
        $('#formTask input').each(function() {
            let $this = $(this);
            
            if(!$this.val()) {
                valid = false;
                $this.parents('.validate').find('.mySpan').text('The '+$this.attr('name').replace(/[\_]+/g, ' ')+' field is required');
            }
        });
    
        if(valid){
            $(".btnSave").text('Saving....').attr('disabled',true);
            let data = $this.serialize();
            $.ajax({
                url: $this.attr("action"),
                type: "POST",
                data: data,
                dataType: "json",
                success: function(resp){
                    if(resp.message == "success"){
                        alert("Saved successful");
                        $("#formTask")[0].reset();
                    }
                    else{
                        alert(resp.message);
                    }
                    $(".btnSave").text('Save').attr('disabled',false);
                },
                error: function(resp){
                    console.log("Something went wrong");
                    $(".btnSave").text('Save').attr('disabled',false);
                }
            });
        }
        return false;
    });
</script>
{% endblock scripts %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Tasky</title>
  {% load static %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  {% block styles %}
  {% endblock styles %}
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <a class="navbar-brand" href="#">Tasky</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto ml-5">
            <!-- <li class="nav-item active">
              <a class="nav-link" href="{% url 'tasks:task'  %}">Add Task <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tasks:view'  %}">View Task</a>
            </li> -->
          </ul>
        </div>
      </nav>

  <!-- Content Wrapper. Contains page content -->
  {% block content %}
  {% endblock content %}
  <!-- /.content-wrapper -->

  

  <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
{% block scripts %}
{% endblock scripts %}
</body>
</html>

templates/products/category.html
<div class="row">
    {% for product in product_image_list %}
    <div class="col-sm-4">
        <img src="{{product.image.url}}" alt="image" width="200" height="200" class="img-responsive">
    </div>
    {% endfor %}
</div>

templates/products/index.html
{% extends 'layout.html' %}

{% block styles %}
<style>
    .text-red{
        color: tomato !important;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-6 offset-3">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                {% for product in product_list %}
                
                <li class="nav-item" role="presentation">
                    <a class="nav-link {% if forloop.counter == 1 %} active {% endif %} category-link" id="{{product.category}}-tab" data-url="{% url 'products:products_category' product.category  %}" data-toggle="tab" href="#{{product.category}}" role="tab" aria-controls="home" aria-selected="true">{{product.category|upper}}</a>
                  </li>
                {% endfor %}
                
                <!-- <li class="nav-item" role="presentation">
                  <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Category</a>
                </li>
                <li class="nav-item" role="presentation">
                  <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Category</a>
                </li> -->
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="mt-4 imageContent">

                </div>
            </div>
            
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    function getFirstCategoryImages()
    {
        let url  = $(".category-link:first").data('url');
        $.ajax({
            url: url,
            type: "GET",
            success: function(resp){
                $(".imageContent").html(resp);
            },
            error: function(resp){
                console.log("something went wrong");
            }
        });
    }

    getFirstCategoryImages();

    $(".category-link").on("click", function(){
        var $this = $(this);
        $.ajax({
            url: $this.data('url'),
            type: "GET",
            success: function(resp){
                $(".imageContent").html(resp);
            },
            error: function(resp){
                console.log("something went wrong");
            }
        });
        return false;
    });
</script>
{% endblock scripts %}

templates/tutorial.html
{% extends 'layout.html' %}

{% block styles %}
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-12 text-center">
            <button class="btn btn-primary btn-get-data">Get HTML file in a div</button>
            <div class="content-data mt-4" data-url="{% url 'tasks:tutorial_data' %}">File content will display here</div>
        </div>
    </div>
</div>



{% endblock content %}

{% block scripts %}
<script>
    $(".btn-get-data").on("click", function(){
        $.ajax({
            url: $(".content-data").data('url'),
            type: "GET",
            success: function(resp){
                $(".content-data").html(resp);
            },
            error: function(resp){
                console.log("something went wrong");
            }
        });
    });
</script>
{% endblock scripts %}

templates/tutorial/index.html
{% extends 'layout.html' %}

{% block styles %}
<style>
    .text-red{
        color: tomato !important;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-6 offset-3">
            
            <form id="formAdd" action="{% url 'tasks:task'  %}" autocomplete="off">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        <div class="form-group validate">
                            <label for="">Category</label>
                            <select name="category" class="form-control">
                                <option value="">--Select--</option>
                                {% for product in product_list %}
                                <option value="{{ product.category }}">{{ product.category }}</option>
                                {% endfor %}
                            </select>
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                        <div class="form-group validate">
                            <label for="">Product</label>
                            <select name="product" class="form-control">
                                <option class="after" value="">--Select--</option>
                            </select>
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    </div>
                    <div class="col-6">
                        <button type="submit" class="btn btn-primary pl-5 pr-5 btnSave">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
   $("#formAdd select[name='category']").on('change', function(){
    var $this = $(this);
    if($this.val() !=''){
        $("#formAdd select[name='product']").find('.after').nextAll().remove();
        $.ajax({
            url: '/tutorial/'+$this.val(),
            type: 'GET',
            success: function(resp){
                let options = '';
                resp.data.forEach(product => {
                    options+='<option value='+product.name+'>'+product.name +'</option>';
                });
                $("#formAdd select[name='product']").find('.after').after(options);
            }, 
            error: function(resp){
                console.log('Something went wrong');
            }
        });
    }else{
        $("#formAdd select[name='product']").find('.after').nextAll().remove();
    }
   });
</script>
{% endblock scripts %}

templates/view.html
{% extends 'layout.html' %}

{% block styles %}
<style>
    .text-red{
        color: tomato !important;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-12">
            <table class="table" id="table">
                <thead>
                  <tr>
                    <th scope="col">Owner</th>
                    <th scope="col">Task</th>
                    <th scope="col">Date</th>
                    <th scope="col">Start</th>
                    <th scope="col">End</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody>
                    {% for task in tasks %}
                    <tr class="record">
                        <td>{{ task.owner }}</td>
                        <td>{{ task.name }}</td>
                        <td>{{ task.task_date }}</td>
                        <td>{{ task.start_time }}</td>
                        <td>{{ task.end_time }}</td>
                        <td>
                            <a href="{% url 'tasks:delete' task.id  %}" class="link-delete text-danger">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
</div>

{% endblock content %}

{% block scripts %}

<script>
$(".link-delete").on("click", function(e){
    e.preventDefault();
    var $this = $(this);
    if(confirm("Sure to delete?")){
        $.ajax({
            url: $this.attr("href"),
            type: "GET",
            dataType: "json",
            success: function(resp){
                if(resp.message == "success"){
                    $this.parents(".record").fadeOut("slow", function(){
                        $this.parents(".record").remove();
                    });
                }else{
                    alert(resp.message);
                }
            }
        });
    }
    return false;
});
</script>

{% endblock scripts %}